TVWatcher/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
    url(r'^people/', include('people.urls')),
    url(r'^tvshows/', include('tvshows.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^', include('movies.urls')),
]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$', views.movies, name='index'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^(?P<movie_id>[0-9]+)/castncrew/$', views.movie_cast, name='movie_cast'),
    url(r'^(?P<movie_id>[0-9]+)/videos/$', views.movie_videos, name='movie_videos'),
    url(r'^(?P<movie_id>[0-9]+)/backdrops/$', views.movie_backdrops, name='movie_backdrops'),
    url(r'^(?P<movie_id>[0-9]+)/posters/$', views.movie_posters, name='movie_posters'),
    url(r'^popular_movies$', views.popular_movies, name='popular_movies'),
    url(r'^top_rated_movies$', views.top_rated_movies, name='top_rated_movies'),
    url(r'^now_playing_movies$', views.now_playing_movies, name='now_playing_movies'),
    url(r'^upcoming_movies$', views.upcoming_movies, name='upcoming_movies'),
]

tvshows/urls.py
from django.conf.urls import url
from . import views

app_name = 'tvshows'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<tvshow_id>[0-9]+)/$', views.tvshow_detail, name='tvshow_detail'),
    url(r'^popular$', views.popular, name='popular'),
    url(r'^top_rated', views.top_rated, name='top_rated'),
    url(r'^on_the_air', views.on_the_air, name='on_the_air'),
    url(r'^airing_today', views.airing_today, name='airing_today'),
    url(r'^(?P<tvshow_id>[0-9]+)/cast&crew/$', views.cast, name='cast'),
    url(r'^(?P<tvshow_id>[0-9]+)/videos/$', views.videos, name='videos'),
    url(r'^(?P<tvshow_id>[0-9]+)/backdrops/$', views.backdrops, name='backdrops'),
    url(r'^(?P<tvshow_id>[0-9]+)/posters/$', views.posters, name='posters'),
]

tvshows/models.py
from django.db import models

# Create your models here.

tvshows/views.py
from django.shortcuts import render, get_object_or_404
import tmdbsimple as tmdb


tmdb.API_KEY = '13866daf0372e25d15b0d1f2d35a2d28'


def index(request):
    popular = tmdb.TV()
    response_popular = popular.popular()
    popular.results = format_date(popular.results[:6])
    popular.results = format_name(popular.results[:6])
    top_rated = tmdb.TV()
    response_top_rated = top_rated.top_rated()
    top_rated.results = format_date(top_rated.results[:6])
    top_rated.results = format_name(top_rated.results[:6])
    on_the_air = tmdb.TV()
    response_on_the_air = on_the_air.on_the_air()
    on_the_air.results = format_date(on_the_air.results[:6])
    on_the_air.results = format_name(on_the_air.results[:6])
    airing_today = tmdb.TV()
    response_airing_today = airing_today.airing_today()
    airing_today.results = format_date(airing_today.results[:6])
    airing_today.results = format_name(airing_today.results[:6])
    return render(request, 'tvshows/index.html', {'popular': popular.results, 'top_rated': top_rated.results,
                                                  'on_the_air': on_the_air.results,
                                                  'airing_today': airing_today.results})


def tvshow_detail(request, tvshow_id):
    tvshow = tmdb.TV(tvshow_id)
    info = tvshow.info()
    images = tvshow.images()
    video = tvshow.videos()['results'][:1]
    if len(video) > 0:
        video_key = video[0]['key']
    else:
        video_key = False
    if len(images['backdrops']) >= 3:
        backdrops = images['backdrops'][:3]
    else:
        backdrops = images['backdrops'][:len(images['backdrops'])]
    cast = tvshow.credits()['cast'][:6]
    directors = []
    return render(request, 'tvshows/details.html', {'tv_show': info, 'images': images, 'video_key': video_key,
                                                    'backdrops': backdrops, 'directors': directors, 'cast': cast})


def cast(request, tvshow_id):
    tvshow = tmdb.TV(tvshow_id)
    response = tvshow.info()
    castandcrew = tvshow.credits()
    cast = castandcrew['cast']
    crew = castandcrew['crew']
    departments = []
    exist = False
    castNoPicture = []
    for member in cast:
        if not member['profile_path']:
            castNoPicture.append(member)
            cast.remove(member)
    for member in crew:
        for department in departments:
            if department == member['department']:
                exist = True
        if not exist:
            departments.append(member['department'])
        exist = False
    return render(request, 'tvshows/cast&crew.html', {'cast': cast, 'crew': crew, 'departments': departments,
                                                     'castNoPicture': castNoPicture})


def popular(request):
    popular_shows = tmdb.TV()
    response = popular_shows.popular()
    popular_shows.results = format_overview(popular_shows.results)
    return render(request, 'tvshows/popular.html', {'popular': popular_shows.results})


def top_rated(request):
    top_rated= tmdb.TV()
    response = top_rated.top_rated()
    top_rated.results = format_overview(top_rated.results)
    return render(request, 'tvshows/top_rated.html', {'top_rated': top_rated.results})


def on_the_air(request):
    on_the_air= tmdb.TV()
    response = on_the_air.on_the_air()
    on_the_air.results = format_overview(on_the_air.results)
    return render(request, 'tvshows/on_the_air.html', {'on_the_air': on_the_air.results})


def airing_today(request):
    airing_today= tmdb.TV()
    response = airing_today.airing_today()
    airing_today.results = format_overview(airing_today.results)
    return render(request, 'tvshows/airing_today.html', {'airing_today': airing_today.results})


def videos(request, tvshow_id):
    tv_show = tmdb.TV(tvshow_id)
    response = tv_show.videos()
    types = []
    exist = False
    for video in tv_show.results:
        for type in types:
            if type == video['type']:
                exist = True
        if not exist:
            types.append(video['type'])
        exist = False
    return render(request, 'tvshows/videos.html', {'videos': tv_show.results, 'types': types})


def backdrops(request, tvshow_id):
    tv_show = tmdb.TV(tvshow_id)
    response = tv_show.images()
    backdrops = response['backdrops']
    return render(request, 'tvshows/backdrops.html', {'backdrops': backdrops})


def posters(request, tvshow_id):
    tv_show = tmdb.TV(tvshow_id)
    response = tv_show.images()
    posters = response['posters']
    return render(request, 'tvshows/posters.html', {'posters': posters})


def format_date(list_items):
    for item in list_items:
        item['first_air_date'] = item['first_air_date'][:4]
    return list_items


def format_overview(list_items):
    for item in list_items:
        item['overview'] = item['overview'][:200] + '...'
    return list_items


def format_name(list_items):
    for item in list_items:
        if len(item['name']) > 20:
            item['name'] = item['name'][:20] + '...'
    return list_items

tvshows/templates/tvshows/airing_today.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for tv_show in airing_today %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/tvshows/{{ tv_show.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/tvshows/{{ tv_show.id }}/"><h4><b>{{ tv_show.name }}</b></h4></a>
                        <span class="rate">{{ tv_show.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ tv_show.first_air_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ tv_show.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

tvshows/templates/tvshows/backdrops.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}

        <div class="container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Backdrops</b></h2></center>
                    </div>
                    {% for backdrop in backdrops %}
                        <div class="col-md-12">
                            <center><a href="http://image.tmdb.org/t/p/original{{ backdrop.file_path }}" target="_blank">
                                <img class="img-responsive" src="http://image.tmdb.org/t/p/w650{{ backdrop.file_path }}">
                            </a></center><br>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

tvshows/templates/tvshows/cast&crew.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}

    <div class="container">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Cast</b></h2></center>
                    </div>
                    {% for member in cast %}
                            <div class="col-md-3">
                                <a href="/people/{{member.id}}/">
                                <img src="http://image.tmdb.org/t/p/w500{{ member.profile_path }}"
                                width="241" height="360">
                                <b>{{ member.name }}</b></a><br>
                                <span style="color:darkgrey">{{ member.character }}</span></h4><br><br>
                            </div>
                    {% endfor %}
                    <div class="col-md-12">
                    </div>
                    {% for member in castNoPicture %}
                            <div class="col-md-3">
                                <a href="/people/{{member.id}}/"><><b>{{ member.name }}</b></a><br><span style="color:darkgrey">{{ member.character }}</span></h4><br>
                            </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Crew</b></h2></center>
                    </div>
                    {% for department in departments %}
                        <div class="col-md-12">
                                <h3>{{ department }}</h3>
                                {% for member in crew %}
                                    {% ifequal member.department department %}
                                        <div class="col-md-3">
                                            <h4><b><a href="/people/{{member.id}}/">{{ member.name }}</a></b>
                                                <br><span style="color:darkgrey">{{ member.job }}</span></h4><br>
                                        </div>
                                    {% endifequal %}
                                {% endfor %}
                         </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>

{% endblock %}

tvshows/templates/tvshows/details.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}

        <div class="container">
                <div class="row">
                        <div class="col-md-3">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <center><img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}"></center>
                                        </div>
                                </div>
                        </div>
                        <div class="col-md-9">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                      <h3><b>{{ tv_show.name }}</b></h3>
                                                </div>
                                                <div class="col-md-12">
                                                    <span><h5><b>Creator(s) : </b>
                                                            {% for member in tv_show.created_by %}
                                                                <a href="/people/{{member.id}}/">
                                                                {{ member.name }} -</a>
                                                            {% endfor %}
                                                            </h5></span>
                                                </div>
                                                <div class="col-md-4">
                                                        <span style="color:darkgrey"><h4>{% for genre in tv_show.genres %}
                                                                                    {{ genre.name }}
                                                                              {% endfor %}</h4></span>
                                                </div>
                                                <div  id="align" class="col-md-4">
                                                        <center><span style="color:darkgrey" class="time">
                                                                <h4><i class="material-icons">access_time</i>
                                                                    {{ tv_show.episode_run_time.1 }} min
                                                                </h4></span></center>
                                                </div>
                                                <div class="col-md-4">
                                                        <span class="pull-right" style="color:darkgrey">
                                                                <span class="date"><h4><i class="material-icons">date_range</i>
                                                                    {{ tv_show.first_air_date }}</h4></span>
                                                        </span>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-9">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-9">
                                                     <h3><b>Overview</b></h3>
                                                </div>
                                                <div class="col-md-12">
                                                     <p>{{ tv_show.overview }}</p>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-12">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                        <a href="/tvshows/{{ tv_show.id }}/cast&crew/"><h3><b>Cast & Crew</b></h3></a>
                                                </div>
                                                {% for member in cast %}
                                                        <div class="col-md-2">
                                                                 <a href="/people/{{member.id}}/">
                                                                 <center><img src="http://image.tmdb.org/t/p/w500{{ member.profile_path }}" c
                                                                              width="156" height="234">
                                                                 <h5><b>{{member.name}}</b></h5></a>
                                                                 <h5>{{member.character}}</h5></center>
                                                        </div>
                                                {% endfor %}
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-12">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                      <div class="col-md-8">
                                                            <a href="/tvshows/{{ tv_show.id }}/videos/"><h3><b>Videos</b></h3></a>
                                                      </div>
                                                      <div class="col-md-2">
                                                              <a href="/tvshows/{{ tv_show.id }}/backdrops/"><h3><b>Backdrops</b></h3></a>
                                                      </div>
                                                      <div class="col-md-2">
                                                              <a href="/tvshows/{{ tv_show.id }}/posters/"><h3><b>Posters</b></h3></a>
                                                      </div>
                                                </div>
                                                <div class="col-md-12">
                                                        <div class="col-md-8">
                                                                {% if video_key %}
                                                                    <iframe allowfullscreen="allowfullscreen"
                                                                            mozallowfullscreen="mozallowfullscreen"
                                                                            msallowfullscreen="msallowfullscreen"
                                                                            oallowfullscreen="oallowfullscreen"
                                                                            webkitallowfullscreen="webkitallowfullscreen"
                                                                            width="600" height="338" src="http://www.youtube.com/embed/{{ video_key }}"
                                                                            frameborder="0"></iframe>
                                                                {% endif %}
                                                        </div>
                                                        <div class="col-md-2">
                                                                {% for backdrop in backdrops %}
                                                                    <img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ backdrop.file_path }}"><br>
                                                                {% endfor %}

                                                        </div>
                                                        <div id="posters" class="col-md-2">
                                                            <br>
                                                                <img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}">

                                                        </div>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
{% endblock %}

tvshows/templates/tvshows/index.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}

        <div class="container">

        <!-- Popular movies -->
        <span class="sort_tvshows"><center><h3><a href="{% url 'tvshows:popular' %}">Popular TV shows</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for tvshow in popular %}
                <div class="col-md-2">
                            <a class="title movie" href="/tvshows/{{ tvshow.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ tvshow.poster_path }}"></a>
                            <a class="title tvshow" href="/tvshows/{{ tvshow.id }}/">{{ tvshow.name }}</a><br>
                            <div class="info">
                                <span class="rate">{{ tvshow.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ tvshow.first_air_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Top rated movies -->
        <span class="sort_tvshows"><center><h3><a href="{% url 'tvshows:top_rated' %}">Top rated TV shows</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for tvshow in top_rated %}
                <div class="col-md-2">
                            <a class="title movie" href="/tvshows/{{ tvshow.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ tvshow.poster_path }}"></a>
                            <a class="title tvshow" href="/tvshows/{{ tvshow.id }}/">{{ tvshow.name }}</a><br>
                            <div class="info">
                                <span class="rate">{{ tvshow.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ tvshow.first_air_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Top on_the_air -->
        <span class="sort_tvshows"><center><h3><a href="{% url 'tvshows:on_the_air' %}">On the air TV shows</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for tvshow in on_the_air %}
                <div class="col-md-2">
                            <a class="title movie" href="/tvshows/{{ tvshow.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ tvshow.poster_path }}"></a>
                            <a class="title tvshow" href="/tvshows/{{ tvshow.id }}/">{{ tvshow.name }}</a><br>
                            <div class="info">
                                <span class="rate">{{ tvshow.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ tvshow.first_air_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Airing today -->
        <span class="sort_tvshows"><center><h3><a href="{% url 'tvshows:airing_today' %}">Airing today TV shows</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for tvshow in airing_today %}
                <div class="col-md-2">
                            <a class="title movie" href="/tvshows/{{ tvshow.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ tvshow.poster_path }}"></a>
                            <a class="title tvshow" href="/tvshows/{{ tvshow.id }}/">{{ tvshow.name }}</a><br>
                            <div class="info">
                                <span class="rate">{{ tvshow.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ tvshow.first_air_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

    </div>
{% endblock %}

tvshows/templates/tvshows/on_the_air.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for tv_show in on_the_air %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/tvshows/{{ tv_show.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/tvshows/{{ tv_show.id }}/"><h4><b>{{ tv_show.name }}</b></h4></a>
                        <span class="rate">{{ tv_show.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ tv_show.first_air_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ tv_show.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

tvshows/templates/tvshows/popular.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for tv_show in popular %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/tvshows/{{ tv_show.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/tvshows/{{ tv_show.id }}/"><h4><b>{{ tv_show.name }}</b></h4></a>
                        <span class="rate">{{ tv_show.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ tv_show.first_air_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ tv_show.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

tvshows/templates/tvshows/posters.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}

        <div class="container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Posters</b></h2></center>
                    </div>
                    {% for poster in posters %}
                        <div class="col-md-12">
                            <center><a href="http://image.tmdb.org/t/p/original{{ poster.file_path }}" target="_blank">
                                <img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ poster.file_path }}"></a>
                            </center><br>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

tvshows/templates/tvshows/top_rated.html
{% extends 'base.html' %}
{% block tvshows_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for tv_show in top_rated %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/tvshows/{{ tv_show.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ tv_show.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/tvshows/{{ tv_show.id }}/"><h4><b>{{ tv_show.name }}</b></h4></a>
                        <span class="rate">{{ tv_show.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ tv_show.first_air_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ tv_show.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}