TVWatcher/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
    url(r'^people/', include('people.urls')),
    url(r'^tvshows/', include('tvshows.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^', include('movies.urls')),
]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$', views.movies, name='index'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^(?P<movie_id>[0-9]+)/castncrew/$', views.movie_cast, name='movie_cast'),
    url(r'^(?P<movie_id>[0-9]+)/videos/$', views.movie_videos, name='movie_videos'),
    url(r'^(?P<movie_id>[0-9]+)/backdrops/$', views.movie_backdrops, name='movie_backdrops'),
    url(r'^(?P<movie_id>[0-9]+)/posters/$', views.movie_posters, name='movie_posters'),
    url(r'^popular_movies$', views.popular_movies, name='popular_movies'),
    url(r'^top_rated_movies$', views.top_rated_movies, name='top_rated_movies'),
    url(r'^now_playing_movies$', views.now_playing_movies, name='now_playing_movies'),
    url(r'^upcoming_movies$', views.upcoming_movies, name='upcoming_movies'),
]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    url(r'^$', views.search, name='search')
]

movies/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

movies/views.py
import datetime

from django.shortcuts import render, get_object_or_404
import tmdbsimple as tmdb


tmdb.API_KEY = '13866daf0372e25d15b0d1f2d35a2d28'


def movies(request):
    popular = tmdb.Movies()
    response_popular = popular.popular()
    popular.results = format_date(popular.results[:6])
    popular.results = format_title(popular.results[:6])
    top_rated = tmdb.Movies()
    response_top_rated = top_rated.top_rated()
    top_rated.results = format_date(top_rated.results[:6])
    top_rated.results = format_title(top_rated.results[:6])
    now_playing = tmdb.Movies()
    response_now_playing = now_playing.now_playing()
    now_playing.results = format_date(now_playing.results[:6])
    now_playing.results = format_title(now_playing.results[:6])
    upcoming = tmdb.Movies()
    response_upcoming = upcoming.upcoming()
    upcoming.results = format_title(upcoming.results[:6])
    return render(request, 'movies/index.html', {'popular_movies': popular.results,
                                                  'top_rated_movies': top_rated.results,
                                                  'now_playing_movies': now_playing.results,
                                                  'upcoming_movies': upcoming.results})


def movie_detail(request, movie_id):
    # Gather and parse basic movie information
    movie = tmdb.Movies(movie_id)
    response = movie.info()
    runtime = movie.runtime
    hours = int(runtime / 60)
    minutes = runtime % 60
    str_minutes = str(minutes)
    if minutes < 10:
        str_minutes = '0' + str(minutes)
    runtime = str(hours) + 'h' + str_minutes
    date = movie.release_date
    genres = ''
    for genre in movie.genres:
        if genres == '':
            genres = genres + genre['name']
        else:
            genres = genres + ', ' + genre['name']
    movie_information = {'id': movie_id, 'title': movie.title, 'runtime': runtime, 'release_date': date, 'overview': movie.overview,
                         'genres': genres, 'poster': movie.poster_path}
    # Get Crew and Cast information
    cast_information = movie.credits()['cast'][:6]
    directors = []
    for member in movie.credits()['crew']:
        if member['job'] == 'Director':
            directors.append(member)
    # Get video, poster and backdrops
    video = movie.videos()['results'][:1]
    if len(video) > 0:
        video_key = video[0]['key']
    else:
        video_key = False
    images = movie.images()
    if len(images['backdrops']) >= 3:
        backdrops = images['backdrops'][:3]
    else:
        backdrops = images['backdrops'][:len(images['backdrops'])]
    # Return information
    return render(request, 'movies/details.html', {'movie_information': movie_information, 'cast': cast_information,
                                                   'crew': directors, 'video_key': video_key, 'backdrops': backdrops})


def movie_cast(request, movie_id):
    movie = tmdb.Movies(movie_id)
    response = movie.info()
    castandcrew = movie.credits()
    cast = castandcrew['cast']
    crew = castandcrew['crew']
    departments = []
    exist = False
    castNoPicture = []
    for member in cast:
        if not member['profile_path']:
            castNoPicture.append(member)
            cast.remove(member)
    for member in crew:
        for department in departments:
            if department == member['department']:
                exist = True
        if not exist:
            departments.append(member['department'])
        exist = False
    return render(request, 'movies/castncrew.html', {'cast': cast, 'crew': crew, 'departments': departments,
                                                     'castNoPicture': castNoPicture})


def movie_videos(request, movie_id):
    movie = tmdb.Movies(movie_id)
    response = movie.videos()
    types = []
    exist = False
    for video in movie.results:
        for type in types:
            if type == video['type']:
                exist = True
        if not exist:
            types.append(video['type'])
        exist = False
    return render(request, 'movies/videos.html', {'videos': movie.results, 'types': types})


def movie_backdrops(request, movie_id):
    movie = tmdb.Movies(movie_id)
    response = movie.images()
    backdrops = response['backdrops']
    return render(request, 'movies/backdrops.html', {'backdrops': backdrops})


def movie_posters(request, movie_id):
    movie = tmdb.Movies(movie_id)
    response = movie.images()
    posters = response['posters']
    return render(request, 'movies/posters.html', {'posters': posters, 'movie_id': movie_id})


def popular_movies(request):
    popular = tmdb.Movies()
    response_popular = popular.popular()
    popular.results = format_date(popular.results)
    popular.results = format_overview(popular.results)
    return render(request, 'movies/popular_movies.html', {'popular_movies': popular.results})


def top_rated_movies(request):
    top_rated = tmdb.Movies()
    response_top_rated = top_rated.top_rated()
    top_rated.results = format_date(top_rated.results)
    top_rated.results = format_overview(top_rated.results)
    return render(request, 'movies/top_rated_movies.html', {'top_rated_movies': top_rated.results})


def now_playing_movies(request):
    now_playing = tmdb.Movies()
    response_now_playing = now_playing.now_playing()
    now_playing.results = format_date(now_playing.results)
    now_playing.results = format_overview(now_playing.results)
    return render(request, 'movies/now_playing_movies.html', {'now_playing_movies': now_playing.results})


def upcoming_movies(request):
    upcoming = tmdb.Movies()
    response_upcoming = upcoming.upcoming()
    upcoming.results = format_overview(upcoming.results)
    return render(request, 'movies/upcoming_movies.html', {'upcoming_movies': upcoming.results})


def format_date(list_items):
    for item in list_items:
        item['release_date'] = item['release_date'][:4]
    return list_items


def format_overview(list_items):
    for item in list_items:
        item['overview'] = item['overview'][:250] + '...'
    return list_items


def format_title(list_items):
    for item in list_items:
        if len(item['title']) > 20:
            item['title'] = item['title'][:20] + '...'
    return list_items

search/views.py
from django.shortcuts import render
import tmdbsimple as tmdb

tmdb.API_KEY = '13866daf0372e25d15b0d1f2d35a2d28'


def search(request):
    search_data = tmdb.Search()
    search_query = request.GET.get("q")
    response = search_data.multi(query=search_query)
    search_data.results = format_title(search_data.results)
    return render(request, 'search/search.html', {'search': search_data.results})


def format_title(list_items):
    for item in list_items:
        if item['media_type'] == 'movie':
            if len(item['title']) > 20:
                item['title'] = item['title'][:20] + '...'
        elif item['media_type'] == 'tv':
            if len(item['name']) > 20:
                item['name'] = item['name'][:20] + '...'
    return list_items

movies/templates/movies/backdrops.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}

        <div class="container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Backdrops</b></h2></center>
                    </div>
                    {% for backdrop in backdrops %}
                        <div class="col-md-12">
                                <center><a href="http://image.tmdb.org/t/p/original{{ backdrop.file_path }}" target="_blank">
                                    <img class="img-responsive"
                                             src="http://image.tmdb.org/t/p/w650{{ backdrop.file_path }}"></a></center><br>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

movies/templates/movies/castncrew.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}

    <div class="container">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Cast</b></h2></center>
                    </div>
                    {% for member in cast %}
                            <div class="col-md-3">
                                <a href="/people/{{member.id}}/">
                                <img src="http://image.tmdb.org/t/p/w500{{ member.profile_path }}"
                                width="241" height="360">
                                <b>{{ member.name }}</b></a><br>
                                <span style="color:darkgrey">{{ member.character }}</span></h4><br><br>
                            </div>
                    {% endfor %}
                    <div class="col-md-12">
                    </div>
                    {% for member in castNoPicture %}
                            <div class="col-md-3">
                                <a href="/people/{{member.id}}/"><p><b>{{ member.name }}</b><br>
                                    <span style="color:darkgrey">{{ member.character }}</span></p></a><br>
                            </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Crew</b></h2></center>
                    </div>
                    {% for department in departments %}
                        <div class="col-md-12">
                                <h3>{{ department }}</h3>
                                {% for member in crew %}
                                    {% ifequal member.department department %}
                                        <div class="col-md-3">
                                            <h4><b><a href="/people/{{member.id}}/">{{ member.name }}</a></b>
                                                <br><span style="color:darkgrey">{{ member.job }}</span></h4><br>
                                        </div>
                                    {% endifequal %}
                                {% endfor %}
                         </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>

{% endblock %}

movies/templates/movies/details.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}

        <div class="container">
                <div class="row">
                        <div class="col-md-3">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <center><img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ movie_information.poster }}"></center>
                                        </div>
                                </div>
                        </div>
                        <div class="col-md-9">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                      <h3><b>{{ movie_information.title }}</b></h3>
                                                </div>
                                                <div class="col-md-12">
                                                    <span><h5><b>Director(s) : </b>
                                                            {% for member in crew %}
                                                                <a href="/people/{{member.id}}/">
                                                                {{ member.name }} -</a>
                                                            {% endfor %}
                                                            </h5></span>
                                                </div>
                                                <div class="col-md-4">
                                                        <span style="color:darkgrey"><h4>{{ movie_information.genres }}</h4></span>
                                                </div>
                                                <div  id="align" class="col-md-4">
                                                        <center><span style="color:darkgrey" class="time">
                                                                {% if movie_information.runtime != '0h00' %}
                                                                        <h4><i class="material-icons">access_time</i>
                                                                        &nbsp;{{ movie_information.runtime }}</h4></span></center>
                                                                {% endif %}
                                                </div>
                                                <div class="col-md-4">
                                                        <span class="pull-right" style="color:darkgrey">
                                                                <span class="date"><h4><i class="material-icons">date_range</i>&nbsp;
                                                                                {{ movie_information.release_date }}</h4></span>
                                                        </span>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-9">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-9">
                                                     <h3><b>Overview</b></h3>
                                                </div>
                                                <div class="col-md-12">
                                                     <p>{{ movie_information.overview }}</p>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-12">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                        <a href="/movies/{{ movie_information.id }}/castncrew/"><h3><b>Cast & Crew</b></h3></a>
                                                </div>
                                                {% for member in cast %}
                                                        <div class="col-md-2">
                                                                 <a href="/people/{{member.id}}/">
                                                                 <center><img src="http://image.tmdb.org/t/p/w500{{ member.profile_path }}"
                                                                              width="156" height="234">
                                                                 <h5><b>{{member.name}}</b></h5></a>
                                                                 <h5>{{member.character}}</h5></center>
                                                        </div>
                                                {% endfor %}
                                        </div>
                                </div>
                        </div>

                        <div class="col-md-12">
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                <div class="col-md-12">
                                                      <div class="col-md-8">
                                                            <a href="/movies/{{ movie_information.id }}/videos/"><h3><b>Videos</b></h3></a>
                                                      </div>
                                                      <div class="col-md-2">
                                                              <a href="/movies/{{ movie_information.id }}/backdrops/"><h3><b>Backdrops</b></h3></a>
                                                      </div>
                                                      <div class="col-md-2">
                                                              <a href="/movies/{{ movie_information.id }}/posters/"><h3><b>Posters</b></h3></a>
                                                      </div>
                                                </div>
                                                <div class="col-md-12">
                                                        <div class="col-md-8">
                                                                {% if video_key %}
                                                                        <iframe allowfullscreen="allowfullscreen"
                                                                                mozallowfullscreen="mozallowfullscreen"
                                                                                msallowfullscreen="msallowfullscreen"
                                                                                oallowfullscreen="oallowfullscreen"
                                                                                webkitallowfullscreen="webkitallowfullscreen"
                                                                                width="600" height="338" src="http://www.youtube.com/embed/{{ video_key }}"
                                                                                frameborder="0"></iframe>
                                                                {% endif %}
                                                        </div>
                                                        <div class="col-md-2">
                                                                {% for backdrop in backdrops %}
                                                                    <img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ backdrop.file_path }}"><br>
                                                                {% endfor %}
                                                        </div>
                                                        <div id="posters" class="col-md-2">
                                                                <br><img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ movie_information.poster }}">
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}
    <div class="container">

        <!-- Popular movies -->
        <span class="sort-movies"><center><h3><a href="{% url 'movies:popular_movies' %}">Popular movies</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for movie in popular_movies %}
                <div class="col-md-2">
                            <a class="title movie" href="/movies/{{ movie.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                            <a class="title movie" href="/movies/{{ movie.id }}/">{{ movie.title }}</a><br>
                            <div class="info">
                                <span class="rate">{{ movie.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ movie.release_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Top rated movies -->
        <span class="sort-movies"><center><h3><a href="{% url 'movies:top_rated_movies' %}">Top rated movies</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for movie in top_rated_movies %}
                <div class="col-md-2">
                            <a class="title movie" href="/movies/{{ movie.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                            <a class="title movie" href="/movies/{{ movie.id }}/">{{ movie.title }}</a><br>
                            <div class="info">
                                <span class="rate">{{ movie.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ movie.release_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Top now playing -->
        <span class="sort-movies"><center><h3><a href="{% url 'movies:now_playing_movies' %}">Now playing movies</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for movie in now_playing_movies %}
                <div class="col-md-2">
                            <a class="title movie" href="/movies/{{ movie.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                            <a class="title movie" href="/movies/{{ movie.id }}/">{{ movie.title }}</a><br>
                            <div class="info">
                                <span class="rate">{{ movie.vote_average }}&nbsp;</span><i class="material-icons md-18">star_rate</i>&nbsp;
                                <span class="release-date">{{ movie.release_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

        <!-- Upcoming -->
        <span class="sort-movies"><center><h3><a href="{% url 'movies:upcoming_movies' %}">Upcoming movies</a></h3></center></span>
        <div class="row">
            <div class="panel panel-default">
             <div class="panel-body">
            {% for movie in upcoming_movies %}
                <div class="col-md-2">
                            <a class="title movie" href="/movies/{{ movie.id }}/">
                                <img width="162" height="243" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                            <a class="title movie" href="/movies/{{ movie.id }}/">{{ movie.title }}</a><br>
                            <div class="info">
                                <span class="release-date">{{ movie.release_date }}&nbsp;</span><i class="material-icons md-18">date_range</i>
                            </div>
                </div>
            {% endfor %}
            </div>
            </div>
        </div>

    </div>
{% endblock %}

movies/templates/movies/now_playing_movies.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for movie in now_playing_movies %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/movies/{{ movie.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/movies/{{ movie.id }}/"><h4><b>{{ movie.title }}</b></h4></a>
                        <span class="rate">{{ movie.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ movie.release_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ movie.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

movies/templates/movies/popular_movies.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for movie in popular_movies %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/movies/{{ movie.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/movies/{{ movie.id }}/"><h4><b>{{ movie.title }}</b></h4></a>
                        <span class="rate">{{ movie.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ movie.release_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ movie.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

movies/templates/movies/posters.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}

        <div class="container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <center><h2><b>Posters</b></h2></center>
                    </div>
                    {% for poster in posters %}
                        <div class="col-md-12">
                            <center><a href="http://image.tmdb.org/t/p/original{{ poster.file_path }}" target="_blank">
                                <img class="img-responsive" src="http://image.tmdb.org/t/p/w500{{ poster.file_path }}">
                            </a></center><br>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

movies/templates/movies/top_rated_movies.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for movie in top_rated_movies %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/movies/{{ movie.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/movies/{{ movie.id }}/"><h4><b>{{ movie.title }}</b></h4></a>
                        <span class="rate">{{ movie.vote_average }}</span>
                        <span><i class="material-icons md-18">star_rate</i></span>
                        <span class="release-date">{{ movie.release_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ movie.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

movies/templates/movies/upcoming_movies.html
{% extends 'base.html' %}
{% block movies_active %}active{% endblock %}
{% block body %}
    <div class="container">

        {% for movie in upcoming_movies %}
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/movies/{{ movie.id }}/"><img width="141" height="212" src="http://image.tmdb.org/t/p/w500{{ movie.poster_path }}"></a>
                    </div>
                    <div class="col-md-8">
                        <a href="/movies/{{ movie.id }}/"><h4><b>{{ movie.title }}</b></h4></a>
                        <span class="release-date">{{ movie.release_date }}</span>
                        <span><i class="material-icons md-18">date_range</i></span><br><br>
                        <p>{{ movie.overview }}</p>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}