TVWatcher/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
    url(r'^people/', include('people.urls')),
    url(r'^tvshows/', include('tvshows.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^', include('movies.urls')),
]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$', views.movies, name='index'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^(?P<movie_id>[0-9]+)/castncrew/$', views.movie_cast, name='movie_cast'),
    url(r'^(?P<movie_id>[0-9]+)/videos/$', views.movie_videos, name='movie_videos'),
    url(r'^(?P<movie_id>[0-9]+)/backdrops/$', views.movie_backdrops, name='movie_backdrops'),
    url(r'^(?P<movie_id>[0-9]+)/posters/$', views.movie_posters, name='movie_posters'),
    url(r'^popular_movies$', views.popular_movies, name='popular_movies'),
    url(r'^top_rated_movies$', views.top_rated_movies, name='top_rated_movies'),
    url(r'^now_playing_movies$', views.now_playing_movies, name='now_playing_movies'),
    url(r'^upcoming_movies$', views.upcoming_movies, name='upcoming_movies'),
]

people/urls.py
from django.conf.urls import url
from . import views

app_name = 'people'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<people_id>[0-9]+)/$', views.people_detail, name='people_detail'),
]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    url(r'^$', views.search, name='search')
]

tvshows/urls.py
from django.conf.urls import url
from . import views

app_name = 'tvshows'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<tvshow_id>[0-9]+)/$', views.tvshow_detail, name='tvshow_detail'),
    url(r'^popular$', views.popular, name='popular'),
    url(r'^top_rated', views.top_rated, name='top_rated'),
    url(r'^on_the_air', views.on_the_air, name='on_the_air'),
    url(r'^airing_today', views.airing_today, name='airing_today'),
    url(r'^(?P<tvshow_id>[0-9]+)/cast&crew/$', views.cast, name='cast'),
    url(r'^(?P<tvshow_id>[0-9]+)/videos/$', views.videos, name='videos'),
    url(r'^(?P<tvshow_id>[0-9]+)/backdrops/$', views.backdrops, name='backdrops'),
    url(r'^(?P<tvshow_id>[0-9]+)/posters/$', views.posters, name='posters'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} TVWatcher {% endblock%}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'movies/style.css' %}"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy|Source+Sans+Pro' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<!----------------------------------- Navigation bar ----------------------------------->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movies:index' %}">TVWatcher</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block movies_active %}{% endblock %}"><a href="{% url 'movies:index' %}"><i class="material-icons">movie</i>&nbsp; Movies</a></li>
                <li class="{% block tvshows_active %}{% endblock %}"><a href="{% url 'tvshows:index' %}"><i class="material-icons">tv</i>&nbsp; TV Shows</a></li>
                <li class="{% block people_active %}{% endblock %}"><a href="{% url 'people:index' %}"><i class="material-icons">star</i>&nbsp; People</a></li>
            </ul>
            <form class="navbar-form navbar-nav" role="search" method="get" action="{% url 'search:search' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="material-icons md-18">search</i></button>
            </form>
        </div>

    </div>
</nav>
<!--------------------------------------- Body ----------------------------------------->
{% block body %}
{% endblock %}
</body>
</html>